name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Python Tests
        run: |
          echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/enterprise-project
            cd ~/enterprise-project
            sudo apt-get update && sudo apt-get install git -y
            if [ -d prometheus.yml ]; then rm -rf prometheus.yml; fi
            if [ ! -d .git ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git pull origin main
            fi
            touch .env
            docker compose down
            docker compose up -d --build
